const countries = [
    // 'United States',
    // 'United Kingdom',
    // 'France',
    // 'Germany',
    // 'Canada',
    // 'Australia',
    // 'India',
    // 'China',
    // 'Japan',
    // 'Brazil',
    // 'Russia',
    // 'South Korea',
    // 'Mexico',
    // 'Italy',
    'Singapore'
];

const cities = {
    // 'United States': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami', 'Atlanta', 'Seattle'],
    // 'United Kingdom': ['London', 'Manchester', 'Edinburgh', 'Birmingham', 'Liverpool', 'Glasgow', 'Bristol'],
    // 'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg'],
    // 'Germany': ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Stuttgart', 'Dusseldorf'],
    // 'Canada': ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg'],
    // 'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Gold Coast'],
    // 'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune'],
    // 'China': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chongqing', 'Tianjin', 'Wuhan'],
    // 'Japan': ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka'],
    // 'Brazil': ['Sao Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Curitiba'],
    // 'Russia': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Samara'],
    // 'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan'],
    // 'Mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Leon', 'Juarez'],
    // 'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Florence', 'Venice', 'Bologna'],
    'Singapore':  [
        "Bedok",
        "Jurong",
        "Tampines",
        "Woodlands",
        "Hougang",
        "Sengkang",
        "Yishun",
        "Ang Mo Kio",
        "Choa Chu Kang",
        "Bukit Merah",
        "Pasir Ris",
        "Bukit Batok",
        "Bukit Panjang",
        "Toa Payoh",
        "Serangoon",
        "Geylang",
        "Punggol",
        "Kallang",
        "Queenstown",
        "Clementi",
        "Bishan",
        "Jurong East",
        "Sembawang",
        "Bukit Timah",
        "Marine Parade",
        "Novena",
        "Outram",
        "Tanglin",
        "Rochor",
        "River Valley",
        "Newton",
        "Downtown Core",
        "Singapore River",
        "Changi",
        "Mandai",
        "Southern Islands",
        "Orchard",
        "Western Water Catchment",
        "Sungei Kadut",
        "Museum",
        "Seletar",
        "Pioneer",
        "Lim Chu Kang",
        "Tuas",
        "North-Eastern Islands",
        "Paya Lebar",
        "Boon Lay",
        "Central Water Catchment",
        "Tengah",
        "Marina East",
        "Marina South",
        "Straits View",
        "Changi Bay",
        "Simpang",
        "Western Islands"
    ]
};

export { countries, cities };